import { SnippetLanguage } from './components/Snippet/snippet.types';

export const LANGUAGES_SELECTOR_LIST: Partial<Record<SnippetLanguage, string>> =
  {
    markup: 'Simple text',
    c: 'C',
    cpp: 'C++',
    csharp: 'C#',
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    coffeescript: 'CoffeeScript',
    python: 'Python',
    go: 'Go',
    java: 'Java',
    json: 'JSON',
    rust: 'Rust',
    php: 'PHP',
    d: 'D',
    dart: 'Dart',
    docker: 'Docker',
    fsharp: 'F#',
    haml: 'Haml',
    haskell: 'Haskell',
    ini: 'Ini',
    kotlin: 'Kotlin',
    less: 'Less',
    lisp: 'Lisp',
    lua: 'Lua',
    nasm: 'NASM',
    objectivec: 'Objective-C',
    powershell: 'Powershell',
    pug: 'Pug',
    r: 'R',
    jsx: 'React JSX',
    tsx: 'React TSX',
    sass: 'Sass',
    scss: 'Scss',
    sql: 'SQL',
    vim: 'Vim',
    yaml: 'YAML',
  };
